### ISSUE TITLE
Control the duration of animations

### ISSUE THREAD

**Issue by RichardPK** [aholachek/react-flip-toolkit#100]
I may be missing something obvious here - but is there a prop to modify the length of time that an animation takes? Not staggering it based on another Flipped component, nor delaying its start - the equivalent of `animation-duration`, or is that actually just to be controlled by the CSS?

**Comment by aholachek** [comment]
Hi, react-flip-toolkit uses springs for animation instead of easings with durations,
[Here's where they're mentioned in the docs](https://github.com/aholachek/react-flip-toolkit#spring-customizations).

There are some ways to play with spring durations, though. [Using this site](https://spring-playground.netlify.com/) you can adjust the "frequency response" variable to your desired duration, then pass in the resulting `stiffness` and `damping` values into the `spring` prop as documented in the first link.

**Comment by RichardPK** [comment]
Nice one thank you!
