### ISSUE TITLE
FLIP animation not occurring while element is in motion

### ISSUE THREAD

**Issue by amitnovick** [aholachek/react-flip-toolkit#102]
Hey @aholachek,
Really cool library!

I think I hit an edge case when using it for a new app.
So I have an element that slides + fades into view using ~~theWeb Animations API~~ CSS keyframes by animating the `transform` and `opacity` properties.

I expected to be able to interrupt this motion, and move the element somewhere else using a FLIP animation, but encountered a problem as there is no animation happening, and the element just teleports immediately to the new position.

I made this minimal reproduction of it, which I would appreciate if you could check out:

## Expected Behaviour
Clicking the purple square while in motion should animate it towards the new position

## Actual Behaviour
Clicking the purple square while in motion triggers no animation, the element is just teleported to the new position.

## Minimal reproduction
CodeSandbox: https://codesandbox.io/s/issue-react-flip-toolkit-element-in-motion-0pvr9

**Comment by aholachek** [comment]
Hi, 

First of all, thank you for making a reproducible test case! Very helpful.

if I understand correctly, the initial animation is the result of a css keyframe. Since the keyframe is in progress when the FLIP animation takes over, you will get overlapping animations. In general, combining CSS animations with JS ones (from the flip library) tends to cause problems. I would explicitly cancel the animate in as soon as the FLIP animation begins, which will hopefully fix the issue.

**Comment by amitnovick** [comment]
> if I understand correctly, the initial animation is the result of a css keyframe. 

Yep, got mixed up with a different piece of code 😅

Thanks for the great explanation!
I followed your suggestion and applied the `animation: slideAndFadeIn 1s; `  property only under a specific state of the element, and that solved it (you can see it working here: https://codesandbox.io/s/issue-react-flip-toolkit-element-in-motion-sl0y2)

Here's the change:

```css
// before
.square {
  animation: slideAndFadeIn 1s;
}

// after
.square[data-state="initial"] {
  animation: slideAndFadeIn 1s;
}
```

Pretty new to web animations in general, so this is just a rudimentary mistake I have now hopefully learned to avoid! 👍
