### ISSUE TITLE
7.0.11 compiler error: "export 'default' (reexported as 'spring') was not found in 'flip-toolkit'"

### ISSUE THREAD

**Issue by mikehobi** [aholachek/react-flip-toolkit#125]
Hello,

I noticed this on a project when updating my packages. And decided to test on a fresh create-react-app.

Any import from `"react-flip-toolkit"` will cause this error:

![image](https://user-images.githubusercontent.com/3231913/84448897-bd0dd800-ac00-11ea-9029-e27a8defdd47.png)

> Failed to compile
>
> ./node_modules/react-flip-tooliit/lib/index.es.js
> "export 'default' (reexported as 'spring') was not found in 'flip-toolkit'

**Comment by aholachek** [comment]
Thank you for catching this! I did a small refactor today and somehow missed the incorrect export in this file (which I've since fixed): https://github.com/aholachek/react-flip-toolkit/blob/master/packages/react-flip-toolkit/src/Spring/index.ts. 

I just released 7.0.12 which should be ok, please let me know if you still have any problems.

**Comment by mikehobi** [comment]
That fixed it! Thank you for fixing so quick, this project is great!
