### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by zackjohnlee** [aholachek/react-flip-toolkit#14]
Getting an error that says: TypeError: Object(...) is not a function. from line 14 of Flipper.js

the error is pointing to the line:
export var FlipContext = createContext("flip");

not sure what this means, I've set up flipper exactly as described. nothing I do seems to alleviate this error.

**Comment by aholachek** [comment]
Hi, are you using React 15.x by any chance? React-flip-toolkit only supports 16+. It's in the docs but it's near the bottom, I should probably make it clearer.
If you are already using 16, I will have to do some digging as I'm having trouble reproducing.

**Comment by zackjohnlee** [comment]
hi, thanks for the quick reply. I am using 16.4.

**Comment by aholachek** [comment]
Hi, unfortunately I have not been able to reproduce this bug on React 16.x.x. The steps I took were:
1. Install fresh project with `create-react-app`, add `react-flip-toolkit`, and implement a small animation. (This worked fine).
2. Downgrade `react` and `react-dom` to 15.x.x.
3. See the same error you're seeing: 
![screen shot 2018-09-06 at 10 55 50 am](https://user-images.githubusercontent.com/3680488/45166077-2eb32980-b1c4-11e8-94c7-9a09e7c1715c.png)
4. Reinstall 16.x.x, error goes away.

Since I can't reproduce I'm going to close the ticket, but if you have a test case please feel free to reopen. Sorry I can't be more helpful.
