### ISSUE TITLE
flipId and flipKey

### ISSUE THREAD

**Issue by dumblole** [aholachek/react-flip-toolkit#27]
Sorry if this is a stupid question, but I have spent many many hours trying to figure out what flipId and flipKey actually do. I've been playing around with the nested example but I'm not sure how the flipId and flipKeys affect the divs. What I'm trying to do is basically the photo-grid example but when the animation finishes (the image is expanded) the page changes using navigateTo() to the actual article url with the text fading in just like the photo-grid example. Going back into history (previous page) would close the article just like the photo-grid and the router-example one. I am using Gatsby Js if that helps. Sorry if this was confusing I can help clarify if needed.

**Comment by aholachek** [comment]
Hi, not a dumb question, probably just a sign that the documentation needs to be improved. 

I think the fact you are trying to do this with Gatsby complicates things. I'm definitely not the expert on this but my personal website is built on Gatsby V2 and I ended up having to use [gatsby-plugin-layout](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/) to get a non-remounting container component that can manage transitions.

It sounds like here the `flipKey` needs to be the url of the page, and the `flipId` needs to be unique for each photo, in order to match each image from a smaller grid component to a larger background component across renders.

**Comment by dumblole** [comment]
Okay, I have flipId covered and I think I can deal with flipKey with a bit of research. Thank you for the quick response and I will ping you if something comes up.

**Comment by dumblole** [comment]
Also, should the flippers be in the actual article page or the list of articles page @aholachek

**Comment by dumblole** [comment]
@aholachek  I just checked it out, but the documentation says that gatsby-plugin-layout was removed in gatsby v2. Is there any other way I could do this?

**Comment by aholachek** [comment]
[gatsby-plugin-layout](https://www.gatsbyjs.org/packages/gatsby-plugin-layout/) was not removed in V2, it was actually added in V2 to replicate the behavior of the V1 layout system. It allows a component (in your case, the `Flipper`) to be persistent across routes, which I think V2 makes difficult/impossible without the layout plugin.

**Comment by dumblole** [comment]
Sorry if i'm being annoying. Just to clarify, should I install the plugin or...?

**Comment by aholachek** [comment]
As far as I know, V2 needs that plugin in order to keep components mounted across route changes. That's a prerequisite for animated page transitions.

I'm going to close this issue as it's not directly about a problem with React Flip Toolkit.
