### ISSUE TITLE
Nested child behaves strangely

### ISSUE THREAD

**Issue by vitalybe** [aholachek/react-flip-toolkit#28]
I've done a really simple example but it seems I missing something, why in this case the child black box doesn't do what I expect: Adjust its position to the expected ending position and instead jumps around?

https://codepen.io/vitalybe/pen/MPbLPW

What am I missing?

**Comment by aholachek** [comment]
Hi Vitaly, [here's a forked example that fixes the problem](https://codepen.io/aholachek/pen/bmBZGJ?editors=0110) (Let me know if this is not what you had in mind!)
By applying the flex styles to the inner `card-content` rather than the outer `card`, the jump is prevented because those styles receive the scale cancellation provided by the `inverseFlipId`.

**Comment by vitalybe** [comment]
Oh! That's definitely what I had in mind. Thank you!

So, is there some rule of thumb about the parent container of `<Flipped>` content? Does it mean the parent container has to be static? What does it mean for more complicated animations?

**Comment by aholachek** [comment]
I think it's more a rule of thumb about any `Flipped` components that use `inverseFlipId`. 

In order to fully cancel out the parent's scale and transform animation, the components with `inverseFlipId` must lie flush with the parent container -- so there can't be any padding or flex styles or other layout styles on the parent, those have to be moved to the child with the `inverseFlipId`.

I need to think about how to communicate this a bit better, then add it to the docs more clearly.
