### ISSUE TITLE
Fade out animation callback is ignoring element's transforms

### ISSUE THREAD

**Issue by vitalybe** [aholachek/react-flip-toolkit#29]
Please see the following example:

https://codesandbox.io/s/qzp4zrr206

Click "Move" and note that the box fade in and moves correctly, but when the times comes to fade out, it jumps back as if the transform did not occur.

I thought it was an issue with animeJS, however, if I comment out the `anime` in fade-out, you can see still that `react-flip-toolkit` puts it there:

https://codesandbox.io/s/w25q9z8o75

After lots of trial and error, I managed to make it work for me, for animeJs example, by setting manually a static transform value in the animation:

`translateY: [0, 0]`

As can be seen here: https://codesandbox.io/s/l2oyv18zrl

**Comment by aholachek** [comment]
Hi, thank you for this detailed issue. 

This is a bug, I think.  [I was able to produce what I think is the correct animation by just using flex-styles on the parent to vertically center the child,  instead of a transform directly on the child](https://codesandbox.io/s/xl5xrvmn2o)

here's what I changed, beyond removing the `transform: translateY` on the box:

```css
.staggered-list-content {
  display: flex;
  align-items: center;
  height: 200px;
}
```

I need to look into why the re-insertion into the DOM performed by `onExit` is not respecting the child's pre-existing transform.
