### ISSUE TITLE
Flipper to support the events like Flipped does

### ISSUE THREAD

**Issue by ConneXNL** [aholachek/react-flip-toolkit#30]
It would be awesome if there are some events on the Flipper object that mimic Flipped' events.

Something like onStartAll, or onCompleteAll?

**Comment by ConneXNL** [comment]
I thought about using that but what if that element isn't even flipping? Additionally, I have multiple flipped instances at different places in the three so it will be very hard to put the event on the correct element.

**Comment by aholachek** [comment]
Good point, I can add this. What, if anything, would you want to pass into the callback functions as arguments?

**Comment by ConneXNL** [comment]
Hmm, not sure if there is anything. Maybe the instance of the Flipper object? Or references to the Flipped objects that are about to be animated/finished animating?

But if there is no use-case for it and it costs additional resources then it's not worth it.

Personally I would use the onStart/onComplete toggle some performance related stuff for smooth shuffling animations.

**Comment by ddfridley** [comment]
Hi, thanks for contributing this.  I want to add a vote for an onComplete callback prop to the Flipper.  I need it because I have other animations that need to happen after this one is complete.  (After all the items in my list settle into place, the panel will smooth scroll to the bottom and show the done button).  It doesn't help to use the onComplete in Flipped because it's hard to know which one will be last.   I'm moving over from react-flip-move and it has an onFinishAll callback.   Think of Flipper as one step in an animation sequence. 

Also, I don't know of anything I would need passed as arguments to the call back functions, I just need to trigger the next thing when this is all complete.

**Comment by aholachek** [comment]
Hi @ddfridley, I've just added `onComplete` to the `Flipper` prop. Hopefully that works for your use case, if not, please let me know!

**Comment by zhiqinyigu** [comment]
Hi  @aholachek , I've found that Flipper's onComplete doesn't call back in some cases. It seems to have something to do with onExit and onAppear, because I always pass them to Fliped.

Oh, I use flip-toolkit. But I repeat this problem in the official example. You can try to pass on the Complete to Flipper,  eg:  `onComplete={() => console.log('Flipper onComplete')}`

This may not be a bug, but at the moment I can't find any more information on this issue and look forward to your prompts. Thank you very much.
