### ISSUE TITLE
Can we use it with React Hooks ?

### ISSUE THREAD

**Issue by collegeimprovements** [aholachek/react-flip-toolkit#33]

**Comment by ConneXNL** [comment]
On a side-note: I haven't looked into react-flip-toolkit's internals, but it seems that internally I could see it use useEffect (that is called AFTER paint) and useLayoutEffect (that is called BEFORE paint). Should be a good practice project to rewrite in order to get used to hooks.

**Comment by aholachek** [comment]
Hi, I don't see any reason why it wouldn't work with hooks, [here's a quick example with `useState`](https://codesandbox.io/s/nkq2m82mk4)

As for refactoring, I'll definitely play around with rewriting it, but I probably won't release the version for quite some time since I wouldn't want to block people using older version of React from using the library, and I'm not sure I can think of any immediate benefits to doing so. (But I haven't spent a lot of time looking at hooks so if there are tangible benefits to a rewrite, please let me know!)

**Comment by jlkiri** [comment]
@ConneXNL  I've been working on a solution that is completely based on React hooks. It is functionally quite similar to this library. Check it out if you're still interested.  
https://github.com/jlkiri/react-easy-flip
