### ISSUE TITLE
Element is tilted slightly after scale animation

### ISSUE THREAD

**Issue by jfurler** [aholachek/react-flip-toolkit#39]
After a scale transition is complete, the flipped element ends up with `transform: matrix(1, 0.0001, -0.0001, 1, 0, 0);`. Presumably, this should be `transform: matrix(1, 0, 0, 1, 0, 0);` (or no transform rule at all). Seems tiny, but it's actually noticeable in certain circumstances.

**Comment by aholachek** [comment]
Thanks for making an issue, I'm leaving the transform to prevent an unpleasant jittering effect that can happen in Chrome when a transform is fully removed from an element. Do you by any chance have an easily available sample to show the noticeable transform? 

Maybe I need to make that configurable.

**Comment by jfurler** [comment]
Yeah, you can see it on https://codesandbox.io/s/zk62k0powp. You'll have to open the fullscreen view, on a wide monitor (or just zoom out a bit). When the search bar is expanded, you can see a dark line up the top right.

Does including a transform of `transform: matrix(1, 0, 0, 1, 0, 0);` still cause the jittering effect?

**Comment by aholachek** [comment]
Thanks for the demo.

Unfortunately `transform: matrix(1, 0, 0, 1, 0, 0);` still causes a jitter, otherwise that would be perfect. I will plan on trying to see if a smaller transform still works and prevents the issue that you're seeing. Otherwise I will make the setting configurable to fully remove the transform. I probably can't get to it immediately but I'll comment here when I've released the fix.

**Comment by aholachek** [comment]
I just released a patch that reduces the rotateZ transform, I'm not positive but playing with your example I **think** it fixes the problem.

**Comment by jfurler** [comment]
Nice, that works great! thanks!
