### ISSUE TITLE
Deformations when animating elements with border radius

### ISSUE THREAD

**Issue by esquevin** [aholachek/react-flip-toolkit#43]
Hi, first thanks for this great library and the excellent documentation and tutorials.

I'm having an issue trying to animate a box with border-radius. When the box change size, a scale transition is done, stretching the border radiuses horribly.
I know that your library allows only to interpolate GPU accelerated properties intentionally, but I keep wondering wether allowing to animate width & height directly might allow the kind of animations that I'm looking for.

You can see what I'm talking about there:
https://codesandbox.io/s/k0p9yo71v

When transitioning the element to the collapsed version, the borders are very pixellated and deformed.

**Comment by aholachek** [comment]
Hey,
You're right that with simple markup you're going to get that warping effect. However, if you're ok doing some more complex markup and CSS, I think you could get closer to the effect you wanted. [I forked your sandbox here](https://codesandbox.io/s/lp940n1v5m) to experiment with separate divs mocking the border radius effect, and I think it might be closer to the effect you intended. However, I needed to have the transform originate from the left to get everything working in concert, I don't know if that is a deal breaker. 

Otherwise you could totally try animating width and height and just using one component that toggles a class with a css transform on width and height rather than 2 separate components -- that's not something this library will probably support ever but I think you might be able to do it with just CSS.

**Comment by esquevin** [comment]
I was currently experimenting with a similar approach https://codesandbox.io/s/mynnkq94z8 but it's not really satisfying either.

I wrote the code in the sandbox to highlight the specific issue of the width animation with border radius, and I could indeed make it work with pure css, but sadly the animation I'm trying to achieve uses a mix of translations and width changes which I cant figure yet how to implement.
Using react-pose I was able to implement a proper animation but encountered other issue that had me try your library
