### ISSUE TITLE
Blurry text after FLIP

### ISSUE THREAD

**Issue by ianschmitz** [aholachek/react-flip-toolkit#51]
After a FLIP is complete, the transformation styles are left on the animated element. This often causes blurry text due to the `transform: translate()` and `transform: scale()` being left on the element.

An approach to fix this would be to remove the styles after the animation is complete. I'm currently trying to manually accomplish using the `onComplete` call back and clearing out the inline styles, however I ran into a road block with #50.

**Comment by aholachek** [comment]
Thanks for making this issue. As an explanation for what probably looks like weird behavior, I left the transform on the element on purpose to prevent an annoying, noticeable "pixel snapping" jump in Chrome (not in firefox or safari) when scale transforms are fully removed from an element. 

I have not been able to replicate a blur from this, are you seeing it in the [codepen you posted for the other issue](https://codepen.io/anon/pen/aPMJaG)? Because it looks fine to me in Chrome and Firefox but obviously if you're seeing a blur there's a problem.

The easiest thing for me to do would be to add a prop to `Flipper`, something like `retainTransform={false}`, to turn this off on a case by case basis. I could also turn it off by default, but I find the jumping at the end of an animation in Chrome distracting. What do you think?

**Comment by ianschmitz** [comment]
Here's a tweak to one of your demos that illustrates the issue: https://codepen.io/anon/pen/MZxoxw.

If you shuffle the list, then use dev tools to disable the inline `transform` style, you can see the text sharpen up.

**Comment by rodrigopr** [comment]
I also had to remove the transform style on `onComplete`, but for another reason.
`transform` creating a new local coordinate system was interfering with a child component (dropdown). 
`retainTransform={false}` would also work for us.

**Comment by aholachek** [comment]
Given that it's causing problems for multiple people, I decided to make a patch release (6.5.3) that just removes the transform for everyone, (it can be added back with `retainTransform={true}`.

Thanks for surfacing this and please let me know if the problem still remains.

**Comment by ianschmitz** [comment]
Hey @aholachek i'm still seeing the `transform` left on the element on 6.5.3. See https://codepen.io/anon/pen/OreqgR

**Comment by aholachek** [comment]
When I go to that link, I only see the identity transform (`matrix(1, 0, 0, 1, 0, 0)`) on the elements, which as far as I know should have no effect on the rendering. Is that still affecting the rendering for you? If so, I can remove it on the final tick.

**Comment by aholachek** [comment]
I'm removing the identity transform as well now so there should be no transform on the element once it's at rest [as you can see here](https://codepen.io/aholachek/pen/NeQWwj). Thanks again for finding this issue.

**Comment by ianschmitz** [comment]
Hey thanks for digging into this @aholachek. 

It seems to be resolved now with `6.5.5`. `transform: matrix(1, 0, 0, 1, 0, 0)` and `transform: scale(1, 1)` seemed to cause rendering issues after the FLIP completed, such as borders of `div` and `input` elements not being rendered correctly, or the occasional blurry text. I notice that there is still `transform: scale(1, 1)` left on the child with `inverseFlipId`, however i haven't noticed any negative effects from it but thought i would point it out.

Thanks again for the quick resolution! 👍

**Comment by cptSwing** [comment]
Should anybody else stumble over this and look for a solution for the odd snapping effect after transforms are removed from an element, here is mine: I dug through 7-year-old versions of this library, and added @aholachek 's  original `transform: matrix(1, 0.00001, -0.00001, 1, 0, 0);` back in a class, which is then overwritten by the style properties react-flip-kit adds when running.

Fixes most of the jitter for me, and does not seem to blur any text in FF as far as I can see. Cheers for the library and take care!
