### ISSUE TITLE
[Question] Integration with "react-modal" (portals again)

### ISSUE THREAD

**Issue by Stanko** [aholachek/react-flip-toolkit#56]
Hello, thank you again for the beautiful library, I have used it on several projects so far.

On the current project we are using [react-modal](https://github.com/reactjs/react-modal) and it is using portals. I'm interested if toolkit can animate between element in the modal and element on the next page (after router transition).

I've tried using `portalKey`, setting it to "ReactModalPortal" (which is the class react-modal uses for it's portals), but with no luck.

[This issue #5](https://github.com/aholachek/react-flip-toolkit/issues/5) had some helpful info, but it uses custom modal implementation, and I couldn't figure out if I can apply the same logic to react-modal.

Don't kill yourself over this :)
Cheers!

EDIT: Example of the transition I'm trying to make :) where modal is in portal which is not rendered on page2
```
______________________          ______________________
|     _________      |          |          |         |
|     | from  |      |          |          | to      |
|     | modal |      |  route   |          | sidebar |
|     |       |      |  change  |          |         |
|     |_______|      |  ---->   |          |         |
|                    |          |          |         |
| page1              |          | page2    |         |
|____________________|          |__________|_________|
```

**Comment by aholachek** [comment]
Hi, thanks for the kind words! Could you check out [this issue](https://github.com/aholachek/react-flip-toolkit/issues/45)?  The unfortunate answer is that if I remember correctly, `react-modal` takes multiple ticks before it renders, which breaks react-flip-toolkit's expectations. A fix from my end would involve react-flip-toolkit having some sort of timeout period while it waits for the new elements to render. The other issue could technically be fixed by the person just using a standard portal instead of react-modal, but obviously that's not the best solution.

**Comment by Stanko** [comment]
Thank you for the fast response! Well, that's a pity. IMHO I think you shouldn't add a timeout option, it just feels like a hack.

Keep up the good work!
