### ISSUE TITLE
Need Help - List Example

### ISSUE THREAD

**Issue by yomeshgupta** [aholachek/react-flip-toolkit#60]
Hi Alex,

Great work on `react-flip-toolkit`. Pretty neat library!

I came across your library and thought of trying it out. I forked your expandable list example and created this https://codesandbox.io/s/w26p07w108

However, I am not able to make it work somehow. 
1. On left side content, first css is applied then animation takes place. I keep `debug: true` then I can see content is aligned to center first then it is being animated to new position.

![initial](https://user-images.githubusercontent.com/20947512/52816356-13c7d800-30c7-11e9-8a11-57f43e60b666.PNG)

![intermediate](https://user-images.githubusercontent.com/20947512/52816363-17f3f580-30c7-11e9-89c7-317c80032e95.PNG)

![final](https://user-images.githubusercontent.com/20947512/52816366-19bdb900-30c7-11e9-919e-befd9d6d43ba.PNG)

2. Whenever text moves around then there is a little squeeze or shrinking of the text (Refer second image left text). Is it because transform or something else? 

Any tips on how to make it more seamless and smooth?
My apologies if these questions sound silly. New to all this animation stuff. 

Thanks in advance though! :D

**Comment by aholachek** [comment]
Hi,

If you don't want the text in the description to warp, even though the container has changed size, you can 1) stop animating scale and only animation translates by adding the `translate` prop, or 2) add another `Flipped inverseFlipId={description}`  wrapping the text and preventing it from scaling with the parent container.

Right now you have css to align the text to the center for one of the two states, that will always cause a jump, I can't see any way to avoid it unless you want to animate each letter individually by wrapping them in spans and then animating them smoothly to the new alignment.

I'm going to close this issue since it doesn't seem to be a problem with the library.

**Comment by yomeshgupta** [comment]
Hi,

Thank you for the response! I will try out your suggestions. And yes, there is no issue with the library. I want able to find your email or DM on twitter that is why raised an issue here. Anyway, library is great. Job well done. Cheers!
