### ISSUE TITLE
Problem when flipper is inside grid

### ISSUE THREAD

**Issue by atomiks** [aholachek/react-flip-toolkit#7]
https://codepen.io/anon/pen/JBpqJr?editors=0010

As you can see with the `debug` property added, the initial inverted transform warps the text.

If I add `translate` or `scale` prop then are problems with the translation. Editing [this pen](https://codepen.io/aholachek/pen/mKXBJR?editors=0010) to remove the flex centering so that the text is positioned in the top-left and use `scale` prop, the text doesn't transition back

**Comment by aholachek** [comment]
Hi! Thank you for making an issue. If you add a style if `inline-block` to the inner container surrounding the text and button, it should work ok.

[Here's a fork of your codepen with the fix.](https://codepen.io/aholachek/pen/vaRddr?editors=0110)

In the pen you posted, the contents of the div were staying the same size, but the div was jumping to a much bigger width when it was in the full screen state, making react-flip-toolkit think that it needed to compress it a lot, creating the warping of the text and button.

Besides that, the other issue with the current example is that, as the full-screen card is animating back down, you see a flash of the next card over because of z index issues. [In other examples I've fixed that by using the `onStart` and `onComplete` callbacks to temporarily add a higher z-index.](https://github.com/aholachek/react-flip-toolkit/blob/7dc38edca398c49f9f2cf4c044f2796d1a5e89c6/demo/src/GuitarsExample/GuitarItem.js#L9)

I'm working on a new major version with some performance improvements and as part of that I'll try to make the documentation about block vs inline styles much clearer, since this is a gotcha.

**Comment by atomiks** [comment]
It works! Yeah, the z-index issue was another thing I noticed but thankfully there's a solution for now.

This library is so insanely good and looked difficult to make, thank you for providing it for us 🙏 .
