### ISSUE TITLE
Synchronize spring animation with another transition

### ISSUE THREAD

**Issue by atomiks** [aholachek/react-flip-toolkit#75]
I'm trying to animate the dimensions of a "popper" (Popper.js) which is an absolutely positioned element positioned near a reference/trigger element. I'm using the `core` part of this library.

The markup is like:

```html
<div class="popper">
  <div class="tooltip">
    <div class="content">...</div>
  </div>
</div>
```

`tooltip` is flipped, and `content` is invertFlipped.

I've been able to FLIP the tooltip's dimensions, but I need to synchronize the spring animation with the popper translation transform.

Basically, if the popper goes from:

```css
.popper {
  transform: translate3d(200px, 100px, 0);
}
```

to:

```css
.popper {
  transform: translate3d(100px, 50px, 0);
}
```

The transition between these translations needs to directly match `react-flip-toolkit`s spring animation in order for it to be positioned correctly throughout the transition.

When the popper's transform has no transition: https://gyazo.com/c0bc2a240de49862df42adba8cfafddb

When the popper's transform has `transition: 0.4s easeOutQuad` (custom cubic bezier of easeOutQuad): https://gyazo.com/55949a68375e64f4328c8f7a030de5cf -- it's sort of close, but not perfect.

Is this possible, or do you have any ideas?

Thanks!

**Comment by aholachek** [comment]
Thanks for making this issue! (Unrelated but I've really enjoyed using tippy.js in my projects).

I've been thinking about adding an additional callback &mdash; `onUpdate` &mdash; that is provided the current spring value for the `Flipped` component. Using this, you could "seek" the `popper`'s transition to a particular point, although I personally don't know of any way to do that with CSS -- I think you'd have to use JS to do the updating to figure out e.g. the point between ` transform: translate3d(200px, 100px, 0);` and  `transform: translate3d(100px, 50px, 0);` that corresponds to a value of `.453` in the spring. 

Would that work for your use case? An earlier version of this library allowed you to specify a duration and a easing function instead of a spring config, which I think would have solved the problem much more easily. But supporting both springs and easing curves is probably not in the cards for me right now as it would make the library bigger and more complicated.

**Comment by atomiks** [comment]
> Unrelated but I've really enjoyed using tippy.js in my projects

Thanks! 😄 

---

Maybe I need to use another spring animation library that controls the `translate` values using a raF loop with identical spring settings to your library?

```js
anime({
  targets: popper,
  translateX: [before, after],
  translateY: [before, after],
  // This function could match `react-flip-toolkit`'s spring animation
  // e.g. `veryGentle`
  easing: 'spring(1, 130, 17, 0)'
});
```

Would need to happen directly after Popper.js applies the new `translate3d()` value to the popper (can be overridden before the change is flushed to the DOM on next paint I think).

I'll give it a try...

**Comment by atomiks** [comment]
Okay so that idea worked (mostly) 🎉 

The springs aren't identical for some reason, but I adjusted it to get close, and the non-perfect match makes it look more natural/organic anyway imo.

react-flip-toolkit: `spring: 'veryGentle'`
animejs: `easing: 'spring(0.9, 125, 13, 0)'`

See here: https://gyazo.com/e85cfdbaba3af190936ce217c98c8e0b

Only one problem I encountered, sometimes (10% of the time) there's a 1-frame "glitch": https://gyazo.com/961b556725469d4929500038566eb12c - is it because there's two separate raF loops (`react-flip-toolkit` + `animejs`) that can schedule changes at different times? Or shouldn't they be batched together?

**Comment by atomiks** [comment]
Yes!! 6.6.0 is perfect. Thank you.

This works perfectly:

```js
let prevData
let currentData

const instance = tippy(button, {
  content: tippyContent,
  placement: 'top',
  interactive: true,
  animateFill: false,
  trigger: 'click',
  maxWidth: window.innerWidth,
  popperOptions: {
    onCreate(data) {
      prevData = currentData = data
    },
    onUpdate(data) {
      prevData = currentData
      currentData = data
    },
  },
})

// ...

flipper.addFlipped({
  element: tooltip,
  onSpringUpdate(value) {
    const { left: prevLeft, top: prevTop } = prevData.popper
    const { left: currentLeft, top: currentTop } = currentData.popper
    const x = prevLeft - value * (prevLeft - currentLeft)
    const y = prevTop - value * (prevTop - currentTop)
    instance.popper.style.transform = `translate3d(${x}px, ${y}px, 0)`
  },
})
```
