### ISSUE TITLE
Question about components that are rendered asynchronously

### ISSUE THREAD

**Issue by EddyVinck** [aholachek/react-flip-toolkit#99]
Hi! Thanks for the cool library! I actually started working on my own implementation for magic move animations, but then I found yours. :slightly_smiling_face: 

I have a question about fetching data asynchronously.

If my `Flipped` on page A has the same ID as the one on page B, but page B fetches some data before rendering `Flipped`, the animation does not happen, which is expected since the destination component has not yet been rendered.

What approach would you recommend here? I was thinking that implementing a skeleton loading state will probably solve this problem.

**Comment by aholachek** [comment]
Hi Eddy,
Right now at least, there is no special handling in react-flip-toolkit for that situation. If you still want a transition, you'd have to keep the old `Flipped` on the screen until the data is ready for the new `Flipped`, and only then update the `flipKey`.

The skeleton loading state idea should work, but only, obviously, if you put an appropriate `Flipped` element there somewhere. Otherwise react-flip-toolkit should silently skip animating. Please let me know if you find any particularly good patterns for this, as I should probably add an example to the docs.

**Comment by EddyVinck** [comment]
@aholachek Thanks for the reply. It will be a while until we get to the point where we will implement the skeleton screens. I'll let you know how it goes.
